---
# needed to populate zone file, a default controller+image install only has the controllers in the hosts file, no drawback to enabling this by default 
- hosts: all
  gather_facts: yes

- hosts: controllers
  gather_facts: no # already done for all
  any_errors_fatal: True
# List of roles to apply to the controllers, in the order in which they will run.
# NOTE: These and their default configurations can be found in the "roles/"
#       directory.

  roles:
    - role: trinity/init
      tags: init
      
    - role: trinity/filesystem
      when: build_zones_from_inventory|bool

    - role: trinity/repos
      repos:
      - repo: '{{ trix_local_repo_baseurl }}'
        name: trinityx-local
      tags: local_repo
      when: local_install

    - role: trinity/repos
      repos:
      - repo: '{{ userspace_repo }}'
      - repo: epel-release
      - repo: '{{luna_repo}}'
      - '{{ohpc_repo_dict}}'
      - '{{ohpc_updates_repo_dict}}'
      tags: repos
      when: 
        - not local_install|bool
        - not enable_repomirror|bool

    - role: trinity/repos
      repos:
      - '{{centos_repo_dict}}'
      - repo: '{{trinity_repo}}'
      - repo: '{{luna_repo}}'
      - repo: '{{zabbix_repo}}'
      - '{{epel_repo_dict}}'
      - '{{ohpc_repo_dict}}'
      - '{{ohpc_updates_repo_dict}}'
      when: enable_repomirror|bool
      tags: repos

    - role: trinity/repos
      repos:
      - { repo: 'http://mirror.nsc.liu.se/centos-store/{{centos_fullvers}}/os/x86_64/', remote_key: 'http://mirror.nsc.liu.se/centos-store/RPM-GPG-KEY-CentOS-7', name: 'CentOS-{{centos_fullvers}}-Base' }
      - { repo: 'http://mirror.nsc.liu.se/centos-store/{{centos_fullvers}}/updates/x86_64/', remote_key: 'http://mirror.nsc.liu.se/centos-store/RPM-GPG-KEY-CentOS-7', name: 'CentOS-{{centos_fullvers}}-Updates' }
      - { repo: 'http://mirror.nsc.liu.se/centos-store/{{centos_fullvers}}/extras/x86_64/', remote_key: 'http://mirror.nsc.liu.se/centos-store/RPM-GPG-KEY-CentOS-7', name: 'CentOS-{{centos_fullvers}}-Extras' }
      - { repo: 'http://mirror.nsc.liu.se/centos-store/{{centos_fullvers}}/centosplus/x86_64/', remote_key: 'http://mirror.nsc.liu.se/centos-store/RPM-GPG-KEY-CentOS-7', name: 'CentOS-{{centos_fullvers}}-centosplusplus' }
      - { repo: 'http://mirror.nsc.liu.se/centos-store/{{centos_fullvers}}/fasttrack/x86_64/', remote_key: 'http://mirror.nsc.liu.se/centos-store/RPM-GPG-KEY-CentOS-7', name: 'CentOS-{{centos_fullvers}}-fasttrack' }
      tags: 
        - repos
      when:
        - use_centos_vault|bool
        - not enable_repomirror|bool
        - not local_install|bool

    - role: trinity/repos
      repos:
      - '{{mellanox_repo_dict}}'
      tags: 
        - mlnx-ofed
        - repos
      when: use_mellanox_ofed|bool

#    - role: trinity/rdma-centos
#      tags: rdma-centos
#      when: not use_mellanox_ofed|bool

#    - role: trinity/mlnx_ofed
#      tags: mlnx-ofed
#      when: use_mellanox_ofed|bool
      
    - role: trinity/cv_support
      tags: cv_support

    - role: trinity/packages
      tags: packages

    - role: trinity/tunables
      tags: tunables

    - role: trinity/hostname
      tags: hostname

    - role: ome.network
      network_ifaces:
      - device: '{{ctrl1_hb_nic}}'
        bootproto: dhcp
        dns1: 8.8.8.8
        dns2: 8.8.4.4
      when: ha and primary|bool and build_zones_from_inventory|bool
      tags: configure-nics

    - role: ome.network
      network_ifaces:
      - device: '{{ctrl2_hb_nic}}'
        bootproto: dhcp
        dns1: 8.8.8.8
        dns2: 8.8.4.4
      when: ha and not primary|bool and build_zones_from_inventory|bool

    - role: trinity/firewalld
      tags: firewalld

    - role: trinity/chrony
      tags: chrony

    - role: trinity/ssh
      tags: ssh

    - role: trinity/fail2ban
      tags: fail2ban

    - role: trinity/pacemaker
      when: ha
      fence_ipmilan_enabled: 'false'
      fence_ipmilan_login: 'user'
      fence_ipmilan_passwd: 'password'
      tags: pcs

    - role: trinity/drbd
      when: ha
      tags: drbd

    - role: trinity/trix-tree
      tags: trix-tree

    - role: trinity/nfs
      nfs_rpccount: 256
      nfs_enable_rdma: false
      nfs_export_shared: true
      nfs_export_home: true
      nfs_exports_path: '{{ trix_local }}/etc/exports.d'
      tags: nfs

    - role: trinity/environment-modules
      when: enable_openhpc == false
      tags: environment-modules

    - role: trinity/pdsh
      when: enable_openhpc == false
      pdsh_conf_path: '{{ trix_local }}/etc/dsh'
      tags: pdsh

    - role: trinity/ssl-cert
      ssl_cert_country: 'UK'
      ssl_cert_locality: 'London'
      ssl_cert_organization: 'Yellowdog'
      ssl_cert_state: 'London'
      ssl_cert_altname: '{{ trix_ctrl_hostname }}.{{ trix_domain }}'
      ssl_cert_days: '3650'
      tags: ssl-cert

    - role: trinity/bind
      bind_db_path: '{{ trix_local }}/var/lib/named'
      bind_dnssec_enable: no
      resolv_server: '{{ trix_ctrl_ip }}'
      tags: bind

    - role: trinity/openldap
      openldap_server_dir_path: '{{ trix_local }}/var/lib/ldap'
      openldap_server_conf_path: '{{ trix_local }}/etc/openldap/slapd.d'
      tags: openldap

    - role: trinity/obol
      users_home_path: '{{ trix_home }}'
      ldap_host: '{{ trix_ctrl_hostname }}.{{ trix_domain }}'
      tags: obol

    - role: trinity/sssd
      sss_allowed_groups:
        - 'admins'
      sss_ldap_hosts:
        - '{{ trix_ctrl_hostname }}.{{ trix_domain }}'
      tags: sssd

    - role: trinity/create-default-users
      tags: create-default-users
      
    - role: trinity/mariadb
      mariadb_db_path: '{{ trix_local }}/var/lib/mysql'
      tags: mariadb

    - role: trinity/openhpc
      nfs_exports_path: '{{ trix_local }}/etc/exports.d'
      when: enable_openhpc == true
      tags: openhpc

    - role: trinity/slurm
      slurm_ctrl: '{{ trix_ctrl_hostname }}'
      slurm_ctrl_ip: '{{ trix_ctrl_ip }}'
      slurm_ctrl_list: '{{ trix_ctrl1_hostname }},{{ trix_ctrl2_hostname }}'
      slurm_conf_path: '{{ trix_shared }}/etc/slurm'
      slurm_spool_path: '{{ trix_local }}/var/spool/slurm'
      munge_conf_path: '{{ trix_shared }}/etc/munge'
      slurmdbd_sql_user: 'slurm_accounting'
      slurmdbd_sql_db: 'slurm_accounting'
      tags: slurm

    - role: trinity/rsyslog
      syslog_listeners:
        - name: default
          proto: tcp
          port: 514
        - name: default
          proto: udp
          port: 514
      syslog_file_template_rules:
        - name: controllers
          type: string
          content: '/var/log/cluster-messages/%HOSTNAME%.messages'
          field: '$fromhost-ip'
          criteria: startswith
          rule: '{{ trix_cluster_net.split(".")[:trix_cluster_netprefix//8]|join(".") }}'
      tags: rsyslog

    - role: trinity/zabbix
      zabbix_path: '{{ trix_local }}/usr/lib/zabbix/'
      zabbix_sql_db: 'zabbix'
      tags: zabbix

#    - role: trinity/zabbix_agent
#      tags: zabbix_agent

    - role: trinity/zabbix_checks
      zabbix_hostmetadata: controller
      tags: zabbix_checks

    - role: trinity/trix-status
      tags: trix-status

    - role: trinity/docker-registry
      when: enable_docker
      docker_registry_path: '{{ trix_local }}/docker-registry'
      docker_ssl_path: '{{ ssl_cert_path }}'
      docker_ssl_cert: '{{ ansible_fqdn }}.crt'
      docker_ssl_key: '{{ ansible_fqdn }}.key'
      tags: docker-registry
    
    - role: trinity/ood-modules
      when: enable_vnc_to_nodes == true
      tags: ood-modules

    - role: trinity/wrapup
      tags: wrapup
