#%Module1.0#####################################################################

#
# @name:    TurboVNC
# @version:  2.2.2
# @packaging: BIOS IT
#

# Customize the output of `module help` command
# ---------------------------------------------
#proc ModulesHelp { } {
#   puts stderr "\tAdds $name to your environment variables"
#   puts stderr "\t\t\$PATH, \$MANPATH"
#}

# Customize the output of `module whatis` command
# -----------------------------------------------
#module-whatis   "loads the [module-info name] environment"

# Define internal modulefile variables (Tcl script use only)
# ----------------------------------------------------------
set   name      TurboVNC
set   version   2.2.2
set   prefix    /opt/ohpc/pub/apps/$name/$version

# Check if the path exists before modifying environment
# -----------------------------------------------------
#if {![file exists $prefix]} {
#   puts stderr "\t[module-info name] Load Error: $prefix does not exist"
#   break
#   exit 1
#}

# Update common variables in the environment
# ------------------------------------------
prepend-path   PATH              $prefix/bin

prepend-path   MANPATH           $prefix/man

setenv         TURBONVNC_DIR     $prefix
